--<ScriptOptions statementTerminator=";"/>

CREATE DATABASE "DB1"
	CCSID EBCDIC;

CREATE  TABLESPACE "TS1"
	IN DB1
	CCSID EBCDIC
	LOCKSIZE ANY
	MAXROWS 255;

CREATE  TABLESPACE "TS2"
	IN DB1
	CCSID EBCDIC
	LOCKSIZE ANY
	MAXROWS 255;

CREATE TABLE "Schema"."TB1" (
		"Col1" CHAR(5), 
		"col2" CHAR(5)
	)
	IN "DB1"."TS1"
	AUDIT NONE
	DATA CAPTURE CHANGES 
	CCSID EBCDIC;

CREATE TABLE "Schema"."TB2" (
		"Col1" CHAR(5), 
		"Col2" CHAR(5)
	)
	IN "DB1"."TS2"
	AUDIT NONE
	DATA CAPTURE NONE 
	CCSID EBCDIC;

